### ISSUE TITLE
Unknown error in das2c_readhttp. dataset: Cassini/Ephemeris/Jupiter

### ISSUE THREAD

**Issue by xandrd** [das-developers/das2dlm#8]
The following example (dataset: Cassini/Ephemeris/Jupiter) results in unknown error in IDL 8.7.2 on Windows:

```
requestUrl = 'http://planet.physics.uiowa.edu/das/das2Server?server=dataset&dataset=Cassini/Ephemeris/Jupiter&start_time=2000-12-29T00:00:00&end_time=2000-12-31T00:00:00&interval=60'
query = das2c_readhttp(requestUrl)
```

Output:

```
% DAS2C_READHTTP: %s
% Execution halted at: $MAIN$
```

All other Cassini/Ephemeris/_datasets_ seems to be working fine

**Comment by cpiker** [comment]
Thanks for the report!

So it looks like the root problem is with the data source not das2dlm, though das2dlm could have done a better job a displaying the error message.  Down in das2C the error message buffer has:
```
Illegal character '!' in identifer 'MLat!DJRM09!N'
```
And dumping the das2 stream itself I see:
```xml
  <y name="MLat!DJRM09!N" units="degrees" type="ascii12" >
    <properties String:yLabel="MLat!DJRM09!N" />
  </y>
```
The value for the `name` field is supposed to be a legal identifier, basically characters that you could use for a variable name in a variety of languages.  This is an invalid stream.

So I see this as two bugs:
 1.  A bad Cassini Ephemeris das2 data source (I'll fix that)
 2. Poor error reporting on the issue from das2dlm (I'll fix that first).

**Comment by xandrd** [comment]
The dataset has been fixed and I was able to load 'Cassini/Ephemeris/Jupiter' data in SPEDAS. 
Should we close this issue? Or, should it be open until better error reporting will be implemented?

**Comment by xandrd** [comment]
Here is an easy way to reproduce the das2c_readhttp error `DAS2C_READHTTP: %s`. The error appears when there is no data on the server, and server return non das2 output, e.g.:
```
No data in the range 1990-01-01 to 1990-01-02
```

IDL code:
```
requestURL = 'http://planet.physics.uiowa.edu/das/das2Server?server=dataset&dataset=Cassini/RPWS/HiRes_MidFreq_Waveform&start_time=1990-01-01&end_time=1990-01-02'
query = das2c_readhttp(requestUrl)
```

**Comment by cpiker** [comment]
This one looks to be fixed, I'll await testing on Windows at least before the bug is closed.

The root cause is that the IDL external interface function `IDL_Message()` looks like a standard VAR_ARGS function (based on it's function signature in idl_export.h) but it actually behaves differently.  Subsequent arguments after the first are ignored!

I've altered the reporting in `das2c_error2idl()` and so das2C messages now make it through to the interpreter.   The stream above is invalid, it outputs an exception header without a stream header and so it should produce an error message.  Here's what I get now with the latest version of the master branch:

```IDL
requestURL = 'http://planet.physics.uiowa.edu/das/das2Server?server=dataset&dataset=Cassini/RPWS/HiRes_MidFreq_Waveform&start_time=1990-01-01&end_time=1990-01-02'
query = das2c_readhttp(requestUrl)
% DAS2C_READHTTP: Unknown top-level descriptor object: exception
                  (Reported from Das2Desc_decode in das2/stream.c:451)
```
Fill free to close the issue once you've verified the new behavior on Windows.

**Comment by xandrd** [comment]
I recompiled the latest version of the library and now I am getting the correct error message.
Tested on Windows, IDL 8.7.2.
